var json_Arq_Hospitais_37 = {
   "type":"FeatureCollection",
   "name":"Arq_Hospitais_37",
   "crs":{
      "type":"name",
      "properties":{
         "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
      }
   },
   "features":[
      {
         "type":"Feature",
         "properties":{
            "Name":"Ambulatorio_Especialidade",
            "layer":"Praça Nove de Julho - Centro SP "
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.350744708535771,
               -23.474987150551993
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Centro_Medico_Diagnostico",
            "snippet":null,
            "layer":"Centro_Medico_Diagnostico"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.352195313694949,
               -23.483369814342336
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Centro Médico São Lucas",
            "snippet":"Rua João Vagnotti, 62 - Centro, Itaquaquecetuba - SP, 08570-220",
            "layer":"Centro_MedicoSaoLucas"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.3517954,
               -23.4740755
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Centro_Saude",
            "snippet":null,
            "layer":"Centro_Saude"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353492667735118,
               -23.480680361706046
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Clinica_mais",
            "layer":"R. Ver. José Barbosa de Araújo, 100-204 - Vila Virginia Itaquaquecetuba - SP 08573-040"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.351550705577019,
               -23.485637841923477
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Clinica_Mulher",
            "snippet":null,
            "layer":"Clinica_Mulher"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353809785801367,
               -23.479026816833709
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Dr_Previna",
            "snippet":null,
            "layer":"Dr_Previna"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.350992334238732,
               -23.474427443798429
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Dr_Previna_Centro",
            "snippet":null,
            "layer":"Dr_Previna_Centro"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.350992090470157,
               -23.474447413394941
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Especialidade_Mulher",
            "snippet":null,
            "layer":"Especiaidade_Mulher"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.352091952750207,
               -23.480293227771842
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Hosp_Kem",
            "layer":"Hospital kemel - itaquaquecetuba - SP"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.362502131214598,
               -23.502257895296705
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Hospital e Maternidade Ipiranga",
            "snippet":"R. Sebastião Ferreira dos Santos, 121 - Centro, Itaquaquecetuba - SP, 08570-060",
            "layer":"Hosp_Maternidade"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.3524959,
               -23.476993
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Hospital Santa Marcelina Itaquaquecetuba",
            "snippet":"R. Rio Negro, 48 - Jardim Nova Itaqua, Itaquaquecetuba - SP, 08599-280",
            "layer":"Hosp_SantaMarcelina"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.3460864,
               -23.4722592
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"hospital_cs",
            "snippet":null,
            "layer":"Hospital_cs"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353585170260523,
               -23.480795081854193
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Hospital_itaqua",
            "layer":"Av. Emancipação, 371 - Centro Itaquaquecetuba - SP 08570-002"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.347945399142432,
               -23.463033146358846
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Laboratorio_Municipal",
            "snippet":null,
            "layer":"Laboratorio_Municipal"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353246662146539,
               -23.480616549083464
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Posto_Saude",
            "layer":"Rua João Vagnotti, 380 - Centro Itaquaquecetuba - SP 08570-630"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353994712319057,
               -23.476123432406638
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Posto_Saude_Morro",
            "layer":"R. Rio Grande do Sul, 585 - Jardim do Algarve Itaquaquecetuba - SP 08572-700"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.3418771452953,
               -23.501856072471107
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Pronto_Socorro",
            "layer":"Av. João Barbosa de Morães - Vila Zeferina Itaquaquecetuba - SP 08576-090"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353457510827667,
               -23.484428354439125
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Pronto_Socorro_Ipiranga",
            "snippet":null,
            "layer":"Pronto_Socorro_Ipiranga"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.352450304489118,
               -23.477055856465931
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Samed_Servico",
            "snippet":null,
            "layer":"Samed_Servico"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.353192177124008,
               -23.483919620773786
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Santa_Casa_Misericordia",
            "snippet":null,
            "layer":"Santa_Casa"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.334312159036593,
               -23.459116549364126
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"UMDI",
            "snippet":null,
            "layer":"UMDI"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.351617770204314,
               -23.47552317073071
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"Upa",
            "layer":"R. João Batista Pedroso, 452 - Res. Flamboyant Itaquaquecetuba - SP 08588-145"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -46.323702905993763,
               -23.439287054809029
            ]
         }
      }
   ]
}